swagger: "2.0"
info:
  description: "This is the upload file api."
  version: "1.0.0"
  title: "Projet fil rouge - API "
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "djan.pirbay@student-cs.fr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "localhost:5000"
basePath: "/v2"
tags:
- name: "File"
  description: "Converts a file into json and returns its metadata"
schemes:
- "https"
- "http"
paths:
  /upload:
    post:
      summary: Uploads a file.
      consumes:
       - multipart/form-data
      parameters:
       - in: formData
         name: upfile
         type: file
         description: The file to upload.
         required: true
      produces:
      - "application/xml"
      - "application/json"
      responses:
        405:
          description: "Invalid input"

