swagger: "2.0"
info:
  description: "This is the upload file api."
  version: "1.0.0"
  title: "Projet fil rouge - API "
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "djan.pirbay@student-cs.fr"
  license:
<<<<<<< HEAD
=======
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: localhost:8000
#basePath: "/"
>>>>>>> 8217d782fbed586aabec5873901da1b62227874b
tags:
- name: "file"
  description: "Converts a file into json and returns its metadata"
schemes:
- "http"
paths:
  /:
    post:
<<<<<<< HEAD
      operationId: app.upload_file
=======
      operationId: app_demo.upload_file
>>>>>>> 8217d782fbed586aabec5873901da1b62227874b
      summary: Uploads a file.
      consumes:
       - multipart/form-data
      parameters:
       - in: formData
         name: file
         type: file
         description: The file to upload.
         required: true
      produces:
      - "application/json"
      responses:
        200:
          description: "File uploaded"
        400:
          description: "bad request"
